Add automated AWS App 2 deployment

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -85,3 +85,45 @@ jobs:
 
           echo "App 1 failed ALB health check."
           exit 1
+                - name: Deploy to AWS App 2
+        env:
+          VERSION: ${{ github.sha }}
+        run: |
+          COMMAND_ID=$(aws ssm send-command \
+            --instance-ids i-0f47649b411b64c55 \
+            --document-name "AWS-RunShellScript" \
+            --parameters "commands=['cd /home/ec2-user/zero-downtime-deployment && git -c safe.directory=/home/ec2-user/zero-downtime-deployment pull origin main && sed -i \"s/\r$//\" deploy-aws.sh && chmod +x deploy-aws.sh && CONTAINER_NAME=app2 SERVER=aws-app2 VERSION=${VERSION:0:7} ./deploy-aws.sh']" \
+            --query "Command.CommandId" \
+            --output text)
+
+          echo "App 2 Command ID: $COMMAND_ID"
+
+          aws ssm wait command-executed \
+            --command-id "$COMMAND_ID" \
+            --instance-id i-0f47649b411b64c55
+
+          aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id i-0f47649b411b64c55
+
+      - name: Check App 2 ALB health
+        run: |
+          for i in {1..20}; do
+            HEALTH=$(aws elbv2 describe-target-health \
+              --target-group-arn "arn:aws:elasticloadbalancing:us-east-1:230355213948:targetgroup/zero-downtime-tg/c365f46e7f025c58" \
+              --targets Id=i-0f47649b411b64c55 \
+              --query "TargetHealthDescriptions[0].TargetHealth.State" \
+              --output text)
+
+            echo "App 2 ALB health: $HEALTH"
+
+            if [ "$HEALTH" = "healthy" ]; then
+              echo "App 2 is healthy."
+              exit 0
+            fi
+
+            sleep 10
+          done
+
+          echo "App 2 failed ALB health check."
+          exit 1
